version: "3.9"

services:
  app:
    build: .
    container_name: travel_planner_app
    ports:
      - "8000:8000"
    environment:
      - API_URL=${API_URL}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: travel_planner_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travel_planner
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
